---
title: "Blogpost"
date: 2019-14-02
---

title: My awesome website
author: Stefan Gerrits
email: myEmail
description: > # this means to ignore newlines until "baseurl:"
  Hello, I like trains.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
